development:
  adapter: mysql
  database: blg
  pool: 5
  timeout: 5000
  user: root

development:
  adapter: mysql
  database: blg_test
  pool: 5
  timeout: 5000
  user: root

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
